version: '3.3'
services:
  webapp:
    build:
      context: ./client
    image: 'tbd_web'
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: ./client
        target: /wwwroot
    environment:
      #This DB connection string needs to match the name of the neo4j service below
      neo4jConnectionString: 'bolt://neo4j'
      CHOKIDAR_USEPOLLING: 'true'

  server:
    build:
      context: ./server
    image: 'tbd_api_server'
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./server
        target: /wwwroot
    environment:
      #This DB connection string needs to match the name of the neo4j service below
      neo4jConnectionString: 'bolt://neo4j'
      CHOKIDAR_USEPOLLING: 'true'

  neo4j:
    image: 'neo4j'
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: volume
        source: data-db
        target: /data
    environment:
      NEO4J_AUTH: 'none'

volumes:
  data-db:
